name: natural_food_store
description: A natural food store app with authentication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.1.0
  go_router: ^10.1.0
  image_picker: ^1.0.7 # Check pub.dev for latest
  provider: ^6.0.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  fl_chart: ^0.71.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    - assets/groceries_banner.png
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/logo.png
    - assets/welcome_background.jpg

fonts:
    - family: BeVietnamPro  # Choose a name for your font family
      fonts:
        # List each font file and specify its weight/style
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400 # Default weight
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700